name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install LLVM dependencies
      run: bash llvm/deps.sh
    - name: Build
      env:
        PATH: /usr/local/bin:${{ env.PATH }}
      run: cargo build --verbose
    - name: Run tests
      env:
        PATH: /usr/local/bin:${{ env.PATH }}
      run: cargo test --verbose
