name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    container: debian:11

    steps:
    - uses: actions/checkout@v4
    - name: Install LLVM dependencies
      run: bash llvm/deps.sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
